name: digit_classification
description: "A Flutter app that uses TensorFlow Lite to recognize handwritten digits using the MNIST model. Users can draw digits on the screen, and the app classifies them in real time."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image: 4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mnist.tflite
